### ISSUE TITLE
Select option is unselectable if the property it maps to is _missing_ from the component's data

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1068]
Say I have the following defined in a schema:
```
favoritePets:
  _label: Favorite Pets
  _has:
    input: select
    multiple: true
    search: true
    options:
      - Cats
      - Dogs
      - Hedgehogs
```

if I have the following set in a bootstrap.yml or a first-run.yml
```
favoritePets:
  Cats: false
  Hedgehogs: false
```
where I am missing a value for the `Dogs` option, I will be unable to select the `Dogs` option in Kiln UX in order to set the value to true. 

Here is an example from a more complicated component:
![metadata](https://user-images.githubusercontent.com/2479295/34127434-252a3958-e40b-11e7-9843-644e048cd5d9.gif)
In this case, we were missing `Book Excerpt: false` in a first-run file which created an instance that was used when creating new pages.
