### ISSUE TITLE
Add `rows` arg to textarea input

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1088]
The `multi-line` text input (textarea) currently defaults to two rows tall, but this should be configurable in component schemas.

```yaml
input: text
type: multi-line
rows: 4
```
