### ISSUE TITLE
Setting `page:true` in a layout schema prevents me from dragging and dropping components more than 1 time

### ISSUE THREAD

**Issue by dmabuada** [clay/clay-kiln#1134]
## Bug
No errors in the console.

I added the following to a layout schema:

```
main:
  _componentList:
    page: true
    include:
      - subscription-offer-message
      - subscription-gift-promo
```

It only allows me to drag and drop one time, but if I remove `page: true`, then it works as expected (but changes persist across pages instead of on a per-page basis).
