### ISSUE TITLE
Filtering complex-list items

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1179]
* ability to filter complex-list items
* how do we generate the index for each item?
* displayed item position should be the index of the item, _not_ the _visible/filtered index_
* maybe think about not allowing add / remove / reorder when filtered (to match filterable-list affordances) (note: remove and reorder are safe, if they make sense to add)
* how does filtering work with collapsing?

idea: you can filter on strings and arrays of strings. you cannot filter on complex-lists, objects, numbers, or any other input types.

```yaml
input: complex-list
props:
  -
    prop: title
    _label: Title
    _has: text
  -
    prop: tags
    _label: Tags
    _has: simple-list
filter:
  - title
  - tags
```
