### ISSUE TITLE
Collapsable complex-list items

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1180]
* allow collapsing complex-list items
* collapsed items display index, title, expand caret
* possibly (depending on the size and functionality) we might display add / remove / reorder buttons
* title is derived from properties of the item
* should we allow only one property? an array of fallbacks? full text interpolation? (KISS)
* what rules does material design have with accordion titles? can they span multiple lines? should they be text-overflow: ellipses?

```yaml
_has:
  input: complex-list
  collapse: primaryHeadline

_has:
  input: complex-list
  collapse:
    - primaryHeadline
    - shortHeadline

_has:
  input: complex-list
  collapse: '${site} | ${primaryHeadline}'
```

![img_0365 2](https://user-images.githubusercontent.com/447522/39019006-e250d240-43f5-11e8-9d3b-09e47ee307ee.JPG)
