### ISSUE TITLE
static input

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1181]
* we should have an input that simply displays static data
* it should allow interpolated text, similar to placeholders
* it should allow attachedButton, label, validation, help, and error messaging
* it should not be editable in the UI
* as it's a real input in a real field, other fields may use magic-buttons to grab data from it
* the styling should emphasize that it's not editable

```yaml
_label: Possible URL
_has:
  input: static
  text: http://www.domain.com/${formattedYear}/${formattedMonth}/${slug}.html
  help: Best-guess generated url
  validate:
    required: true
    requiredMessage: Please fill out date and slug to generate url
  attachedButton: custom-url-generator-plugin-button
```
