### ISSUE TITLE
when creating components, all children should be cloned

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1218]
Currently when creating components that have child references in their default data, the child is only cloned if their uri is to the default instance, e.g.

```yaml
_ref: /_components/parent
content:
  _ref: /_components/child
```

If you specify a non-default child instance, it's _not cloned_, but rather referenced directly, e.g.

```yaml
_ref: /_components/parent
content:
  _ref: /_components/child/instances/foo
```

Zoe and I think that, while this made sense when most of our data was hand-coded in bootstrap files, it creates invisible links between those child components (which might exist on wildly different pages), and so we should change this behavior to _always_ clone children.

This would also allow devs to specify _different_ child defaults based on the parent, e.g.

```
# child default data
_ref: /_components/child
componentVariation: child

# specific child instance
_ref: /_components/child/instances/foo
componentVariation: child_large

# parent default data
_ref: /_components/parent
content:
  _ref: /_components/child/instances/foo
```

This only solves for when the parent is added. https://github.com/clay/clay-kiln/issues/1169 might be the solution for adding those specific children afterwards (though that might be automated by...)

## Automatically selecting child instance to clone from

```yaml
_componentList:
  include:
    - child
    - other-child/instances/foo
```

The issue with this approach is that:

* End users cannot select what instance they want to add when adding new children (an issue that Named Component Instances does not have)
* Data is directly referenced in the schema, which is not something we do elsewhere (at least not to this scale. we do reference site slugs, and conditional required / _reveal may reference data, but it's not as tightly coupled as this would be)
