### ISSUE TITLE
Bug: Reveal not triggered in a complex list

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#1225]
I have a complex list where each item has a single checkbox, and additional fields are shown using reveal behavior when the checkbox has been checked. The very first time I open the pane to edit the list, the reveal behavior on the checkbox is not being triggered. After closing and reopening everything works as expected.

This only happens when none of the items in the list have the checkbox checked. When at least one item is checked reveal behavior works as expected. This was also working as expected a couple of weeks ago (when it was initially developed).

Example schema:

```
articleSlots:
  _label: Article Slots
  _has:
    input: complex-list
    props:
      -
        prop: override
        _label: Override Article
        _has:
          input: checkbox
      -
        prop: overrideUrl
        _label: Override URL
        _has:
          input: text
          type: url
        _reveal:
          field: override
          value: true
```
