### ISSUE TITLE
_reveal prop multi-compare values

### ISSUE THREAD

**Issue by dmabuada** [clay/clay-kiln#1234]
It'd be nice if we could could compare a prop to multiple values, e.g:

```
_reveal:
  field: revealProp
  compare: '!=='
  value:
    - 'subscription-page'
    - 'newsletter-page'
```

**Comment by nelsonpecora** [comment]
Hmm, I think there are two parts to this (or rather, two use cases):

* compare multiple values (using implicit OR, since you run the comparator against each one and match if any succeed)
* compare multiple _fields_ (much more complicated)

Comparing against multiple values would have to use a different `value` property, as arrays are perfectly valid values to compare against. Probably something like:

```yaml
_reveal:
  field: revealProp
  compare: '!=='
  values:
    - 'subscription-page'
    - 'newsletter-page'
```
