### ISSUE TITLE
Text read as number for validate max

### ISSUE THREAD

**Issue by cruzanmo** [clay/clay-kiln#1244]
## Bug

schema:
```
        prop: text
        _label: Link Text
        _has:
          input: wysiwyg
          buttons:
            - italic
            - strike
          enforceMaxlength: true
          validate:
            required: true
            max: 30
```

Enter a number in the text field, e.g. `31` and the validate max says it is invalid.

![image](https://user-images.githubusercontent.com/22883/41309822-bd7d7414-6e4d-11e8-9c97-cea06392f5e0.png)
