### ISSUE TITLE
Optional Display Name in Component Schema

### ISSUE THREAD

**Issue by yuliyv** [clay/clay-kiln#1257]
It would be helpful when developing install specific components (i.e. components for a particular site built with clay) to be able to specify a custom "display name" instead of whatever the actual name for a component is.  For example if we were to build a component name: `nym-image` it will appear in clay as "Nym Image" which might be confusing for those using the Kiln UI.  Instead it would be preferable to be able to create properly namespaced components, but choose the way those components appear in the UI.

One way this could be implemented would be an additional parameter in the component schema that looks like the following:

`components/nym-image/schema.yml`
```yml
version: 0.1
description: |
  NYM Specific Image Container
displayName: Image
...
```
