### ISSUE TITLE
Trigger Render of Editing Modal on Complex List Add / Remove

### ISSUE THREAD

**Issue by yuliyv** [clay/clay-kiln#1258]
The way kiln currently handles `_reveal` logic with `complex-list` inputs means it's challenging to build editing experiences that react to the addition / removal of elements from the list.

Consider the following sample schema file:

```yml
description: |
  Sample Component

collection:
  _has:
    input: complex-list
    props:
      -
        prop: data
        _label: Data
        _has:
          input: text
          help: Some sample data

collectionLayout:
  _label: Sample Collection Layout
  _has:
    input: text
  _reveal:
    field: collection.length
    operator: '>'
    value: 0

_groups:
  settings:
    fields:
      - collection
      - collectionLayout
```

In this example we see that the component has a property `collectionLayout` which is conditionally rendered based on the length of the `collection` complex list.  With the current way Kiln works this `_reveal` logic is not triggered when elements are added/removed from the `collection` complex list so a user must close the editing modal and re-open it before the `_reveal` logic is executed.  Ideally instead this `_reveal` logic would be triggered as soon as elements are added / removed from the list

**Comment by nelsonpecora** [comment]
Hmm, we don't currently support that `collection.length` field property, which is why it's probably only being run when it's checking the store rather than the current field. Checking lengths is an interesting feature request, but it looks like in this instance you really only care if the list is not empty, correct? You can do that with the `not-empty` operator (no value required).

**Comment by yuliyv** [comment]
This is perhaps a too simplified example, here's a more robust example of what I am trying to achieve:

```yml
description: |
  Sample Component

collection:
  _has:
    input: complex-list
    props:
      -
        prop: data
        _label: Data
        _has:
          input: text
          help: Some sample data url

collectionLayout:
  _label: Sample Collection Layout
  _has:
    input: segmented-button-group
    options:
      - title: 2 Images
        values:
          - icon: icon-thumbnail.svg
            text: Two Vertical
            value: two-vertical
          - icon: icon-thumbnail.svg
            text: Two Square
            value: two-square
        _reveal:
          field: collection.length
          operator: '==='
          value: 2
      - title: 3 Images
        values:
          - icon: icon-thumbnail.svg
            text: Three Vertical
            value: three-vertical
          - icon: icon-thumbnail.svg
            text: Three Square
            value: three-square
        _reveal:
          field: collection.length
          operator: '==='
          value: 3
  _reveal:
    field: collection.length
    operator: '>'
    value: 0

_groups:
  settings:
    fields:
      - collection
      - collectionLayout
```

For this specific use case @byronhulcher suggested that a more canonical approach would be adding a [reveal operator](https://github.com/clay/clay-kiln/blob/master/lib/utils/comparators.js#L3) for something like `lengthOf` since there are likely many use cases like the above which would benefit from that default.

In general though this might have come from of a misunderstanding of the documentation for the `_reveal` property, since it [appears to not suggest any caveats about deep field comparisons](https://claycms.gitbooks.io/kiln/editing-components.html#reveal).  It makes sense since `length` isn't really a "kiln" property, but just a property of arrays in general, so I think it would be beneficial to maybe change the logic to block unexpected fields from ever triggering the reveal logic if that's the intended behavior.

I think it makes sense to still track this issue and try to make the following changes:

1. Update documentation to explain the difference between Kiln schema and JS properties in deep field comparisons
2. Throw a warning/error when Kiln detects usage of a non-Kiln property in a deep field comparison
