### ISSUE TITLE
_reveal doesn't work for checkbox-group

### ISSUE THREAD

**Issue by markerberg** [clay/clay-kiln#1285]
**Main issue**
The `_reveal` functionality doesn't work as expected on checkbox-groups. We have to manually save the component to see our `_reveal` field, it doesn't toggle instantaneously. `_reveal` works perfectly with checkboxes, just not checkbox-group 

**Setup**
```
deviceTypes:
  _label: Include in These Feeds
  _has:
    input: checkbox-group
    options:
      - name: Alexa
        value: alexaVoice
      - name: Apple
        value: appleVoice
```
```
alexaSponsorId:
  _label: Alexa Sponsor Id
  _has:
    input: text
  _reveal:
    field: deviceTypes.alexaVoice
    operator: ===
    value: true
```
**Steps to Reproduce**

1) With the setup above, toggling the checkbox-group(`deviceTypes`) to true should reveal the input field(`alexaSponsorId`) but it doesn't at first.
<img width="596" alt="screen shot 2018-07-30 at 1 23 18 pm" src="https://user-images.githubusercontent.com/10458251/43412682-facf09c6-93fb-11e8-93d6-b45dc9bb2cde.png">
<img width="601" alt="screen shot 2018-07-30 at 1 23 39 pm" src="https://user-images.githubusercontent.com/10458251/43412684-fadd0a80-93fb-11e8-92a6-021b84f57ffb.png">

2) To reveal the input field, we must manually save the component. Once we save the component and reopen it, the reveal logic is applied.
<img width="604" alt="screen shot 2018-07-30 at 1 24 12 pm" src="https://user-images.githubusercontent.com/10458251/43412685-faeb6d5a-93fb-11e8-9b76-612eaf4fce0f.png">
