### ISSUE TITLE
Expandable Component List

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1287]
Acceptance Criteria

- [x] I can expand a component to reveal child components. 
- [x] I can collapse the parent component.

**Comment by nelsonpecora** [comment]
### Notes

* _all_ component list placeholders should display `text`
* when empty, displays like a normal component list placeholder (config'd height, Add Button)
* when filled, displays like a small placeholder with dropdown caret
* on load, content is collapsed by default

### Config

```yaml
_placeholder:
  text: Scenarios
  height: 600px
  collapse: true
```
