### ISSUE TITLE
'validate + required` with `field + values` does not... validate

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1340]
I have a component list with the following `prop`:
```
      -
        prop: attribution
        _label: Attribution
        _has:
          input: wysiwyg
          buttons:
            - link
            - italic
            - bold
          validate:
            required:
              field: type
              operator: ===
              values:
                - quote
                - comment
                - external
        _reveal:
          field: type
          operator: ===
          values:
            - quote
            - comment
            - external
```

The validation does not work when using `values` but when switching to `value` it does work.
