### ISSUE TITLE
ability to set a default value for a prop on a complex-list input i.e. a checkbox: true

### ISSUE THREAD

**Issue by phillyDesignr** [clay/clay-kiln#1494]
## Is your feature request related to a problem? Please describe.

We need the ability to set checkbox: true on a input: checkbox in a complex-list similarly to setting options in a checkbox-group

## Describe the solution you'd like

something like
```
_has:
  input: checkbox
    -
      checked: true
```

## Describe alternatives you've considered

none

## Additional context

n/a
