### ISSUE TITLE
Persist Quill alignment options 

### ISSUE THREAD

**Issue by salomoneb** [clay/clay-kiln#1557]
## Description

[Quill has](http://quilljs.com/docs/modules/toolbar/) an `align` option. Specifying this creates a button which allows you to choose a text alignment. 
<img src="https://user-images.githubusercontent.com/16308025/211368836-8181d27d-ff95-47d7-8936-2c97e08fb393.png" width=500/>

I added this to my inline form input like so: 
```yml
overrideHeadline:
  _label: Headline
  _publish: articleHeadline
  _placeholder:
    height: 40px
  _has:
    input: inline
    buttons:
      - italic
      - strike
      # https://github.com/quilljs/quill/issues/1969#issuecomment-389697111
      - align: ["", "center", "right"]
```

I can align the text through the editor, but the alignment doesn't persist on save. Demo: 

https://user-images.githubusercontent.com/16308025/211367335-c116e57e-0782-4b6b-b814-dea0f9d693c1.mov

There's a `ql-align-*` class that gets added to the Quill wrapper class while editing, but which gets stripped on save in [inputs/wysiwyg-sanitize.js](https://github.com/clay/clay-kiln/blob/master/inputs/wysiwyg-sanitize.js#L83). 

@james-owen and I talked over Slack about adding a [`transformTags`](https://www.npmjs.com/package/sanitize-html#user-content-transformations) function to `wysiwyg-sanitize.js` that would look for the special Quill alignment classes and add the alignment preferences as inline styles to the parent text element: 
> grab all paragraphs, grab their styles, if they match our list add them to parent element, strip p tags. 

## Expected Behavior

Kiln should save my alignment preference.
