### ISSUE TITLE
Placeholder does not work with _component property

### ISSUE THREAD

**Issue by cperryk** [clay/clay-kiln#751]
A placeholder does not appear when a `_component` property is set for a schema field.

Example schema:
```
someRef:
  _placeholder:
    height: 50px
    text: My Placeholder
  _display: inline
  _component:
    include:
      - clay-paragraph
```

Example nunjucks template:
```
<div data-uri="{{ _ref or _self }}" class="test">
  <div data-editable="someRef">
    {{ embed(state.getTemplate('component'), someRef, state) | safe }}
  </div>
</div>
```

I also noticed that the `_component` field is not listed in the section "Field Properties" of the [behaviors documentation](https://github.com/nymag/clay-kiln/tree/master/behaviors).
