### ISSUE TITLE
Idea: Improved descriptions for Conditional Required behavior

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#920]
## Idea
Currently the descriptions for the conditional-required behavior are not as clear as they perhaps could be.  Here's an example:
```
teaser:
  _label: Editorial Teaser
  _has:
    - label
    - textarea
    - 
      fn: description
      value: A short description of the listing
    -
      fn: conditional-required
      field: brandTeaser
      operator: empty

brandTeaser:
  _label: Brand Provided Teaser
  _has:
    - label
    - textarea
    - 
      fn: description
      value: A short description of the listing provided by the brand
    -
      fn: conditional-required
      field: teaser
      operator: empty
```
When I create a new empty component with these fields I see the following:
<img width="582" alt="screen shot 2017-09-26 at 1 34 46 pm" src="https://user-images.githubusercontent.com/2479295/30874845-8b0f2860-a2bf-11e7-9a02-535c9a3d78cd.png">

In this case it might be better if each read `Required (when [other field name] is empty)`? I imagine each of the different operators would need its own custom description for this.
